/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/BoardTile")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class BoardTile : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "300f2e09ed171a44ca4da82ece6a38bb";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_type = "Default";
        [SerializeField] public System.Boolean m_rotatePiece = false;
        [SerializeField] public UnityEngine.Vector3 m_targetRotation = new Vector3(0, 0, 0);

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_type),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_rotatePiece),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_targetRotation),
            };
        }
    }
}

#endif
