/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Board")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class Board : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b04add8f445bded44b756b3d2d44fd22";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_piecesGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_matchmakerGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_cardManagerGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_playerHudGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_audioManagerGameObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_piecesGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_matchmakerGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_cardManagerGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_playerHudGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_audioManagerGameObject),
            };
        }
    }
}

#endif
