/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GenericText")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class GenericText : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "4cf7a9c3f01d9fa4bbe400b2a1afcfe8";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_isHeading = false;
        [SerializeField] public System.Boolean m_isSmall = false;
        [SerializeField] public System.Boolean m_isTiny = false;
        [SerializeField] public System.String m_label = "";
        [SerializeField] public System.Boolean m_applyCustomColor = false;
        [SerializeField] public UnityEngine.Color m_customColor = new Color(0, 0,0,0);

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_isHeading),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_isSmall),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_isTiny),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_label),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_applyCustomColor),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_customColor),
                CreateSerializedProperty(_script.GetPropertyAt(6), null),
            };
        }
    }
}

#endif
