/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GenericTextProxy")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class GenericTextProxy : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "fd3ac50a7aec5dc4fbdd998b7e4ed0e7";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.MeshRenderer m_meshRenderer = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_meshRenderer),
            };
        }
    }
}

#endif
