/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Matchmaker")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class Matchmaker : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "2d21149addecb2b4cac5bad0c4d79a2f";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_raceGame = default;
        [SerializeField] public UnityEngine.GameObject m_cameraRoot = default;
        [SerializeField] public UnityEngine.GameObject m_playGameHandlerGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_playerHudGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_cardManagerGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_audioManagerGameObject = default;
        [SerializeField] public UnityEngine.Vector3 m_cameraWaitingAreaRotation = new Vector3(0, 0, 0);
        [SerializeField] public UnityEngine.Vector3 m_cameraGameRotation = new Vector3(0, 0, 0);

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_raceGame),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_cameraRoot),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_playGameHandlerGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_playerHudGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_cardManagerGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_audioManagerGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_cameraWaitingAreaRotation),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_cameraGameRotation),
            };
        }
    }
}

#endif
