/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PlayGameHandler")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class PlayGameHandler : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "99c929f4ec92120408b9486cca9e4815";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_matchmakerGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_raceGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_audioManagerGameObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_matchmakerGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_raceGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_audioManagerGameObject),
            };
        }
    }
}

#endif
